### ISSUE TITLE
Function to write ROI to existing file 

### ISSUE THREAD

**Issue by clbarnes** [bhoeckendorf/pyklb#4]
`writefull` requires you to be willing/ able to store the whole array in RAM, which is not always the case. Overwriting a region (or mutating it by reading it, transforming and writing back) would be useful.

**Comment by bhoeckendorf** [comment]
This operation is not supported by KLB and there are currently no plans to implement it.

The main issue is that it is impossible to predict the size of the updated block after compression. KLB stores blocks in a predefined order. If the updated block occupies more space than its original counterpart, then there is not enough space in the file for it to fit into its place within that order. As a result, updating a single block would require re-writing substantial portions of the file.

Of course, one solution would be to allow storing blocks in any order. In that case, if the updated block is too big it could simply be appended to the end of the file. But this results in fragmentation issues that negatively impact file size and reading performance.
