### ISSUE TITLE
Add support for numpy 1.12

### ISSUE THREAD

**Issue by rueberger** [bhoeckendorf/pyklb#5]
When you get the chance could you add support for numpy 1.12? Thanks!

**Comment by jakirkham** [comment]
Appears the conda recipe was added in PR ( https://github.com/bhoeckendorf/pyklb/pull/1 ). Is this conda package something that you are still maintaining, @stuarteberg, or do you know if someone else is? If it is being maintained, is this something that is going to be migrated to conda-forge?

**Comment by bhoeckendorf** [comment]
Making setuptools/distutils play nicely with cython and cmake is more tricky than it seems it should be, and I do not have a lot of experience with conda, but I'll give conda-forge a try. It seems as if that would be the most hassle-free slolution for everyone. (If it works...)

**Comment by jakirkham** [comment]
Thanks for taking a look @bhoeckendorf. More than happy to help you with the ropes. [conda-forge]( http://conda-forge.github.io/ ) has done a pretty good job of sweeping the clutter that goes into building under the rug. To get started, I'd take a look at [this]( http://conda-forge.github.io/#add_recipe ) and there is a longer FAQ at the [staged-recipes]( https://github.com/conda-forge/staged-recipes ) repo.

In general, conda-forge packages tagged releases. So it might be worth checking if you like the tags you have now. We can of course try with a development version and tag once the build is working if you would like. It looks like `klb` has a pretty recent tag. So maybe that one is ok to run with as is. In the case of `pyklb`, looks like the last tag was a year ago. Not sure if there are important changes that you would want to get in the conda-forge package, but it might be worth thinking about. We can discuss if you would like.

Also it looks like @stuarteberg has done a very nice job with the [`klb` recipe]( https://bitbucket.org/fernandoamat/keller-lab-block-filetype/src/3e2cd65e06d5d8ee645c8fa09a8b707e0ffd7e12/src/conda-recipe/?at=v0.3.4 ). It would need a few tweaks as that recipe appears to be designed for development use and conda-forge is focused on stable releases, but we can discuss more in a PR. As for `pyklb`, I'd suggest taking the [existing recipe]( https://github.com/bhoeckendorf/pyklb/tree/870874e26129411382323467d62038456bcb0385/conda-recipe ) and adjust it to something along the lines of this [`zwatershed`]( https://github.com/conda-forge/zwatershed-feedstock/blob/9678aeffe8b35904c052bed193ac61410997b956/recipe/meta.yaml ) recipe.

**Comment by rueberger** [comment]
Thanks @jakirkham!! @bhoeckendorf, I got what I need from numpy 1.12, this is no longer urgent.
